import type { PitchScorecard } from "@/types";
import jsPDF from "jspdf";

const SECTION_ORDER = [
  "STARTUP NAME",
  "PROBLEM",
  "SOLUTION",
  "TARGET MARKET",
  "BUSINESS MODEL",
  "KEY RISKS",
  "WHAT TO DO NEXT",
] as const;

export function parseBriefSections(briefText: string) {
  const sections = SECTION_ORDER.reduce<Record<string, string>>((acc, key) => {
    acc[key] = "";
    return acc;
  }, {});

  let currentSection: string | null = null;

  for (const rawLine of briefText.replace(/\r/g, "").split("\n")) {
    const line = rawLine.trim();

    if (!line) {
      continue;
    }

    const cleanLineForMatch = line.toUpperCase().replace(/^[#*\s]+/, "");
    const matchedSection = SECTION_ORDER.find((section) =>
      cleanLineForMatch.startsWith(section),
    );

    if (matchedSection) {
      currentSection = matchedSection;
      const regex = new RegExp(`^[#*\\s]*${matchedSection}[:*\\s-]*`, "i");
      sections[matchedSection] = line.replace(regex, "").trim();
      continue;
    }

    if (currentSection) {
      sections[currentSection] = sections[currentSection]
        ? `${sections[currentSection]}\n${line}`
        : line;
    }
  }

  if (!sections["STARTUP NAME"]) {
    sections["STARTUP NAME"] = inferStartupName(briefText);
  }

  return sections;
}

function inferStartupName(sourceText: string) {
  const cleaned = sourceText
    .replace(/[^a-zA-Z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .join(" ");

  return cleaned || "Untitled Startup";
}

export function generateInvestorBrief(
  briefText: string,
  startupIdea: string,
  scorecard?: PitchScorecard,
) {
  const doc = new jsPDF({ format: "a4", unit: "mm" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 16;
  const contentWidth = pageWidth - marginX * 2;
  const parsedSections = parseBriefSections(briefText || startupIdea);

  doc.setFillColor(13, 13, 13);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(21);
  doc.setTextColor(240, 237, 230);
  doc.text("PITCHPK", marginX, 20);

  doc.setFont("courier", "bold");
  doc.setFontSize(9);
  doc.setTextColor(224, 64, 32);
  doc.text("INVESTOR BRIEF", marginX, 27);

  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  doc.setTextColor(142, 142, 142);
  doc.text(new Date().toLocaleDateString(), pageWidth - marginX, 17, {
    align: "right",
  });

  doc.setDrawColor(224, 64, 32);
  doc.setLineWidth(0.5);
  doc.line(marginX, 32, pageWidth - marginX, 32);

  let y = 42;

  if (scorecard) {
    doc.setFillColor(18, 18, 18);
    doc.roundedRect(marginX, y - 2, contentWidth, 18, 2.5, 2.5, "F");

    doc.setFont("courier", "bold");
    doc.setFontSize(8);
    doc.setTextColor(224, 64, 32);
    doc.text("SCORE SNAPSHOT", marginX + 4, y + 3);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(240, 237, 230);
    doc.text(`${scorecard.overall}/100`, marginX + 4, y + 10);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.text(
      `${scorecard.readinessLabel} · Survival ${scorecard.survivalRate}% · Heat ${scorecard.roastTemperature}% · Dodged ${scorecard.questionsDodged}`,
      marginX + 28,
      y + 10,
    );

    doc.setFontSize(8);
    doc.setTextColor(176, 176, 176);
    doc.text(scorecard.biggestRisk, marginX + 4, y + 15);

    y += 24;
  }

  SECTION_ORDER.forEach((section) => {
    const content =
      parsedSections[section] ||
      (section === "STARTUP NAME"
        ? inferStartupName(startupIdea)
        : "Not enough data from the session.");

    doc.setFont("courier", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(224, 64, 32);
    doc.text(section, marginX, y);
    y += 4.2;

    doc.setFont("helvetica", section === "STARTUP NAME" ? "bold" : "normal");
    doc.setFontSize(section === "STARTUP NAME" ? 13 : 9.4);
    doc.setTextColor(240, 237, 230);

    const lines = doc.splitTextToSize(content, contentWidth);
    doc.text(lines, marginX, y, { baseline: "top" });
    y += lines.length * 4.2 + 4.4;
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Generated by PitchPK · pitchpk.vercel.app",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" },
  );

  doc.save("pitchpk-investor-brief.pdf");
}
